In [2]:
#Imports

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# Set figure aesthetics
sns.set_style("white", {'ytick.major.size': 8.0})
sns.set_context("poster", font_scale=1.0)

c:\Anaconda3\lib\site-packages\matplotlib\__init__.py:872: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))


In [3]:
responses = pd.read_csv('Responses.csv')

In [9]:
responses.drop(responses.columns[0],axis=1,inplace=True)

In [10]:
responses.values

array([[ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,   5.,  nan, ...,   4.,   5.,   1.],
       ..., 
       [ nan,   6.,   5., ...,  nan,   4.,  nan],
       [  6.,  nan,   6., ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan]])

In [12]:
import nimfa

In [17]:
import numpy as np
import scipy.sparse as spr

import nimfa

V = spr.csr_matrix([[1, 0, 2, 4], [0, 0, 6, 3], [4, 0, 5, 6]])
print('Target:\n%s' % V.todense())

nmf = nimfa.Nmf(V, max_iter=200, rank=2, update='euclidean', objective='fro')
nmf_fit = nmf()

W = nmf_fit.basis()
print('Basis matrix:\n%s' % W.todense())

H = nmf_fit.coef()
print('Mixture matrix:\n%s' % H.todense())

print('Euclidean distance: %5.3f' % nmf_fit.distance(metric='euclidean'))

sm = nmf_fit.summary()
print('Sparseness Basis: %5.3f  Mixture: %5.3f' % (sm['sparseness'][0], sm['sparseness'][1]))
print('Iterations: %d' % sm['n_iter'])
print('Target estimate:\n%s' % np.dot(W.todense(), H.todense()))

Target:
[[1 0 2 4]
 [0 0 6 3]
 [4 0 5 6]]
Basis matrix:
[[ 3.87325866  0.00843274]
 [ 5.43041999  0.        ]
 [ 7.68650235  0.        ]]
Mixture matrix:
[[  3.34247036e-01   0.00000000e+00   7.60437823e-01   7.52151852e-01]
 [  0.00000000e+00   0.00000000e+00   5.23003416e-04   0.00000000e+00]]
Euclidean distance: 12.940
Sparseness Basis: 0.543  Mixture: 1.000
Iterations: 16
Target estimate:
[[ 1.29462522  0.          2.94537679  2.91327867]
 [ 1.81510178  0.          4.12949675  4.08450045]
 [ 2.56919063  0.          5.84510711  5.78141698]]


In [19]:
import numpy as np

import nimfa

V = responses.values
print('Target:\n%s' % V)

lsnmf = nimfa.Lsnmf(V, max_iter=100, rank=20)
lsnmf_fit = lsnmf()

W = lsnmf_fit.basis()
print('Basis matrix:\n%s' % W)

H = lsnmf_fit.coef()
print('Mixture matrix:\n%s' % H)

print('K-L divergence: %5.3f' % lsnmf_fit.distance(metric='kl'))

print('Rss: %5.3f' % lsnmf_fit.fit.rss())
print('Evar: %5.3f' % lsnmf_fit.fit.evar())
print('Iterations: %d' % lsnmf_fit.n_iter)
print('Target estimate:\n%s' % np.dot(W, H))

Target:
[[ nan  nan  nan ...,  nan  nan  nan]
 [ nan  nan  nan ...,  nan  nan  nan]
 [ nan   5.  nan ...,   4.   5.   1.]
 ..., 
 [ nan   6.   5. ...,  nan   4.  nan]
 [  6.  nan   6. ...,  nan  nan  nan]
 [ nan  nan  nan ...,  nan  nan  nan]]


OverflowError: Range exceeds valid bounds